"""
LLM Factory — returns the correct LangChain chat model based on LLM_PROVIDER.

All agents call get_llm() instead of instantiating a model directly.
Switch providers by changing LLM_PROVIDER in .env — no code changes needed.
"""
from functools import lru_cache
from langchain_core.language_models import BaseChatModel
from backend.app.core.config import settings


@lru_cache(maxsize=1)
def get_llm(temperature: float = 0.2) -> BaseChatModel:
        # Hugging Face Transformers + LoRA
        if provider == "hf_lora":
            from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
            from peft import PeftModel, PeftConfig
            import torch

            model_name = settings.HF_MODEL_NAME
            use_lora = settings.USE_LORA
            lora_path = settings.LORA_ADAPTER_PATH

            tokenizer = AutoTokenizer.from_pretrained(model_name)
            if use_lora and lora_path:
                base_model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map="auto")
                model = PeftModel.from_pretrained(base_model, lora_path)
            else:
                model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map="auto")

            pipe = pipeline(
                "text-generation",
                model=model,
                tokenizer=tokenizer,
                device=0 if torch.cuda.is_available() else -1,
                max_new_tokens=512,
                temperature=temperature,
            )

            class HuggingFaceChatModel(BaseChatModel):
                def _call(self, messages, stop=None, run_manager=None, **kwargs):
                    prompt = "\n".join([m.content for m in messages])
                    result = pipe(prompt)[0]["generated_text"]
                    return result
                @property
                def _llm_type(self) -> str:
                    return "hf_lora"

            return HuggingFaceChatModel()
    provider = settings.LLM_PROVIDER.lower()
    print(f"[DEBUG] LLM_PROVIDER at runtime: {settings.LLM_PROVIDER}")
    print(f"[DEBUG] GROQ_MODEL at runtime: {getattr(settings, 'GROQ_MODEL', None)}")

    if provider == "ollama":
        try:
            from langchain_ollama import ChatOllama
        except ImportError:
            from langchain_community.chat_models import ChatOllama
        
        return ChatOllama(
            model=settings.OLLAMA_MODEL,
            base_url=settings.OLLAMA_BASE_URL,
            temperature=temperature,
        )

    elif provider == "openai":
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(
            model="gpt-4o",
            api_key=settings.OPENAI_API_KEY,
            temperature=temperature,
        )

    elif provider == "azure_openai":
        from langchain_openai import AzureChatOpenAI
        return AzureChatOpenAI(
            azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
            azure_deployment=settings.AZURE_OPENAI_DEPLOYMENT,
            api_version=settings.AZURE_OPENAI_API_VERSION,
            api_key=settings.AZURE_OPENAI_API_KEY,
            temperature=temperature,
        )

    elif provider == "mock":
        from langchain_core.language_models import SimpleChatModel

        class MockChatModel(SimpleChatModel):
            @property
            def _llm_type(self) -> str:
                return "mock"
            def _call(self, messages, stop=None, run_manager=None, **kwargs):
                return "**[Mock Response Active]**\n\nThe AI model provider has been globally bypassed due to network/token constraints. The PMO Agentic framework successfully constructed the context, parsed the React form data, and routed the workflow to this agent step natively! Your application is fully working end-to-end.\n\n*(This is a placeholder response generated by the Mock Agent to unblock your workflow without calling a real LLM)*"
                
        return MockChatModel()

    elif provider == "gemini":
        from langchain_google_genai import ChatGoogleGenerativeAI
        return ChatGoogleGenerativeAI(
            model=settings.GEMINI_MODEL,
            temperature=temperature,
            google_api_key=settings.GOOGLE_API_KEY
        )

    elif provider == "groq":
        from langchain_groq import ChatGroq
        return ChatGroq(
            model=settings.GROQ_MODEL,
            temperature=temperature,
            groq_api_key=settings.GROQ_API_KEY
        )

    else:
        raise ValueError(
            f"Unknown LLM_PROVIDER='{provider}'. "
            "Valid options: ollama | openai | azure_openai | gemini | mock"
        )
